//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_device_type_t {
  vx_device_type_specific_device = 0,
  vx_device_type_default_system = 1,
  vx_device_type_null = 2,
  vx_device_type_default_communication = 3
}

}
