//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_opus_bandwidth {
  opus_bandwidth_auto = 0,
  opus_bandwidth_nb = 1,
  opus_bandwidth_mb = 2,
  opus_bandwidth_wb = 3,
  opus_bandwidth_swb = 4,
  opus_bandwidth_fb = 5
}

}
