//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_recording_frame_type_t {
  VX_RECORDING_FRAME_TYPE_DELTA = 0,
  VX_RECORDING_FRAME_TYPE_CONTROL = 1
}

}
