//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_session_media_state {
  session_media_disconnected = 1,
  session_media_connected = 2,
  session_media_ringing = 3,
  session_media_connecting = 6,
  session_media_disconnecting = 7
}

}
