//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_udp_frame_type {
  vx_frame_type_rtp = 0,
  vx_frame_type_rtcp = 1,
  vx_frame_type_sip_message = 2,
  vx_frame_type_sip_keepalive = 3
}

}
