//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_participant_type {
  participant_user = 0,
  part_user = participant_user,
  participant_moderator = 1,
  part_moderator = participant_moderator,
  participant_owner = 2,
  part_focus = participant_owner
}

}
