//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_password_hash_algorithm_t {
  password_hash_algorithm_cleartext = 0,
  password_hash_algorithm_sha1_username_hash = 1
}

}
