//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_session_answer_mode {
  mode_none = 0,
  mode_auto_answer = 1,
  mode_verify_answer = 2,
  mode_busy_answer = 3
}

}
