//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_sessiongroup_playback_control_type {
  VX_SESSIONGROUP_PLAYBACK_CONTROL_STOP = 0,
  VX_SESSIONGROUP_PLAYBACK_CONTROL_START = 1,
  VX_SESSIONGROUP_PLAYBACK_CONTROL_PAUSE = 3,
  VX_SESSIONGROUP_PLAYBACK_CONTROL_UNPAUSE = 4
}

}
