//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum VXA_CAPTURE_FLAGS {
  VXA_CAPTURE_OPEN_FLAG_USE_AEC = 0x00000001,
  VXA_CAPTURE_OPEN_FLAG_USE_AGC = 0x00000002
}

}
